In [3]:
#Imports

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
URL = "https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD"
# import du fichier
local_file = "data/fremont.csv"

from pathlib import Path

if Path(local_file).exists():
    print(f"le fichier {local_file} est déjà là")
else:
    print(f"allons chercher le fichier {local_file}")

    import requests
    req = requests.get(URL)

    # doit afficher 200
    print(req.status_code)

    # on sauve tel quel dans le fichier local
    with open(local_file, 'w') as writer:
        writer.write(req.text)

#!head $local_file

le fichier data/fremont.csv est déjà là

In [4]:
#Chargement

# version naïve
data = pd.read_csv(local_file)
data.shape
data.head()

,Date,Fremont Bridge Total,Fremont Bridge East Sidewalk,Fremont Bridge West Sidewalk
0,08/01/2022 12:00:00 AM,23.0,7.0,16.0
1,08/01/2022 01:00:00 AM,12.0,5.0,7.0
2,08/01/2022 02:00:00 AM,3.0,0.0,3.0
3,08/01/2022 03:00:00 AM,5.0,2.0,3.0
4,08/01/2022 04:00:00 AM,10.0,2.0,8.0

In [5]:
#Doublons

!grep '01/01/2014 12:00:00 AM' $local_file

data.drop_duplicates(inplace=True)

data.shape
#On a deux fois moins de lignes

01/01/2014 12:00:00 AM,23,5,18
01/01/2014 12:00:00 AM,23,5,18

(87600, 4)

In [6]:
#Echauffement

sample_dates = pd.to_datetime([
    "2024-01-15 08:00:00",
    "2024-01-20 17:30:00",
    "2024-02-03 12:00:00",
])

#print(type(sample_dates))
# C'est un type pandas.DatatimeIndex

print(sample_dates)

#print(sample_dates.date)
# Ceci renvoie la partie "date" des éléments de temps dans sample_dates
# Les éléments du tableau renvoyé sont des datetime.date

# print(sample_dates.time)
# Renvoie la partie "heure" au format 24h
# Les éléments du tableau renvoyé sont des datetime.time

# print(sample_dates.dayofweek)
# Renvoie des entiers int32 entre 0 et 6 du jour de la semaine

# print(sample_dates.year)
# en int32

DatetimeIndex(['2024-01-15 08:00:00', '2024-01-20 17:30:00',
               '2024-02-03 12:00:00'],
              dtype='datetime64[us]', freq=None)

In [7]:
#Dates après 20 janvier 2024
#On utilise un masque de booléens:



Post20janvier24=sample_dates[sample_dates>=pd.to_datetime("2024-01-20 00:00:00")]
#print(Post20janvier24)

# On a bien les dates après le 20 janvier 2024. Les objets DatetimeIndex peuvent être comparés.

EnJanvier24=sample_dates[sample_dates>=pd.to_datetime("2024-01-01 00:00:00")][sample_dates<=pd.to_datetime("2024-01-31 00:00:00")]
print(EnJanvier24)

DatetimeIndex(['2024-01-15 08:00:00', '2024-01-20 17:30:00'], dtype='datetime64[us]', freq=None)

In [14]:
#Parser les dates

#data.info()
#data.dtypes

#Transformer la colonne Date en DatetimeIndex

data['Date']=pd.to_datetime(data['Date'])

#data.info()
#On a bien converti la colonne Date en format datetime64[us]

data.index=pd.to_datetime(data.Date,format="%m/%d/%Y %I:%M:%S %p")

#data.info()

del data["Date"]

data.columns=['Total','West','East']

KeyError: 'Date'

In [16]:
#Renommons les colonnes

data.columns = ['Total', 'West', 'East']

data.head()

                     Total  West  East
Date
2022-08-01 00:00:00   23.0   7.0  16.0
2022-08-01 01:00:00   12.0   5.0   7.0
2022-08-01 02:00:00    3.0   0.0   3.0
2022-08-01 03:00:00    5.0   2.0   3.0
2022-08-01 04:00:00   10.0   2.0   8.0

In [ ]:
#Données manquantes et extension types

LignesIncompletes=data[data.isna().any(axis=1)]


LignesIncompletes.head()

                     Total  West  East
Date
2013-03-10 02:00:00    NaN   NaN   NaN
2013-06-14 09:00:00    NaN   NaN   NaN
2013-06-14 10:00:00    NaN   NaN   NaN
2014-03-09 02:00:00    NaN   NaN   NaN
2015-03-08 02:00:00    NaN   NaN   NaN